Repository CS3219-SE-Principles-and-Patterns/cs3219-project-ay2122-2122-s1-g15, pull requests merged in 2021-11, with the labels that each got.

#72 [Deployment] Setup Google Cloud CI/CD for Frontend
  api-gateway/Dockerfile
  cloudbuild.yaml
  docker-compose.yml
  frontend/app/.env
  frontend/app/Dockerfile
  frontend/app/package-lock.json
  frontend/app/package.json
  frontend/app/src/App.js
  frontend/app/src/api/matching.js
  frontend/app/src/components/Header.js
  frontend/app/src/components/matching/MatchingPage.js
  frontend/app/src/components/session/SessionPage.js
  frontend/app/src/components/session/chat/ChatBox.js
  frontend/app/src/components/session/editor/Editor.js
  frontend/app/src/components/session/question/QuestionBox.js
  frontend/app/yarn.lock
  knote-ingress-tls.crt
  knote-ingress-tls.key
  kubernetes/chat.yaml
  kubernetes/client.yaml
  kubernetes/editor.yaml
  kubernetes/ingress.yml
  kubernetes/matching.yaml
  services/chat/api/routes.js
  services/chat/index.js
  services/editor/index.js
  services/matching/.env
  services/matching/api/controller.js
  services/matching/api/routes.js
  services/matching/api/validation.js
  services/matching/docs/activity_match_submit.puml
  services/matching/docs/activity_ux.puml
  services/matching/docs/model_matchrequest.puml
  services/matching/docs/model_questions.puml
  services/matching/docs/sequence_cancel.puml
  services/matching/docs/sequence_find-match.puml
  services/matching/docs/sequence_match-submit.puml
  services/matching/index.js
  services/matching/package-lock.json
  services/matching/package.json
  services/matching/services/db.js
  services/matching/services/service.js
  services/matching/test/data.js
  services/matching/test/test.js
Labels: Priority - High

#95 Deploy editor
  frontend/app/src/components/session/editor/Editor.js
  services/editor/index.js
  services/editor/package-lock.json
  services/editor/package.json
  services/editor/services/db.js
  services/editor/services/service.js
  services/editor/test_env.js
  services/editor/tests/test.js
Labels: Deployment

#112 Add READMEs and clean up code
  .github/workflows/nodejs.yml
  .travis.yml
  README.md
  frontend/app/README.md
  frontend/app/images/peerprep.png
  k6_script.js
  services/chat/README.md
  services/editor/README.md
  services/editor/api/connectionController.js
  services/editor/api/routes.js
  services/editor/index.js
  services/editor/services/db.js
  services/editor/services/service.js
  services/editor/tests/test.js
  services/matching/README.md
  services/matching/package.json
Labels: documentation
